### ISSUE TITLE
Group chat |Add member | Not able to check checkbox 

### ISSUE THREAD

**Issue by jagdish-vayuz** [Bitovn/Bridge-issues#103]

**Comment by technicalbirdVayuz** [comment]
<input type="checkbox" class="checkbox-input" id="check_{{email}}" />
                      <label class="checkbox-input" for="check_{{email}}"></label>

Here in checkbox, Id & for combination works for checkbox, you need to make both both have same id but different from others. So, I have passed email as the unique id & its working
