### ISSUE TITLE
chat | file upload and emoji icon not visible in send message box

### ISSUE THREAD

**Issue by jagdish-vayuz** [Bitovn/Bridge-issues#105]
![Screenshot from 2022-09-12 10-05-36](https://user-images.githubusercontent.com/84120381/189574916-35457e6d-514e-4cb6-8a53-8079b7308f37.png)

**Comment by technicalbirdVayuz** [comment]
Icons are made visible. You are not supposed to use head tag inside template tag

**Comment by technicalbirdVayuz** [comment]
Also, the font awesome  file you have is having some issues, it does not load icons,. Added new link from CDN
