### ISSUE TITLE
Chat> reaction modal> User profiles who liked the msg did not appear

### ISSUE THREAD

**Issue by Anupriyabanger** [Bitovn/Bridge-issues#170]
![image](https://user-images.githubusercontent.com/109590553/196457280-eaa29b6f-302a-4914-bacb-5527f0d63bc2.png)

**Comment by Anupriyabanger** [comment]
![image](https://user-images.githubusercontent.com/109590553/198016134-e2ac2c46-2fc4-4639-9d2e-795b0b4d1551.png)
@bidyut-majumdar please display modal like this.

**Comment by bidyut-majumdar** [comment]
@Anupriyabanger currently we are using the same reaction modal approach for social as well as Insight. So we will decide if we need to clone/copy team's style.
