### ISSUE TITLE
chat list> add status text on hover

### ISSUE THREAD

**Issue by Anupriyabanger** [Bitovn/Bridge-issues#173]
![image](https://user-images.githubusercontent.com/109590553/196460468-ebf1c3c8-b794-420c-a5d1-97f8072df835.png)

**Comment by bidyut-majumdar** [comment]
@jagdish-vayuz I have added the code pattern for tooltip (but not being displayed, might be caused due to bootstrap.js not loading, also all type of status can be integrated now.
