### ISSUE TITLE
chat> showing msg in wrong chat

### ISSUE THREAD

**Issue by Anupriyabanger** [Bitovn/Bridge-issues#177]
1. Search option not working properly.
2. Sent a text to Shikhar but showed this text in different users chatbox 

![image](https://user-images.githubusercontent.com/109590553/196467916-8ae5692d-a61f-423c-bd32-82a32a9eaee0.png)
![image](https://user-images.githubusercontent.com/109590553/196468251-6e03434c-e3dc-481e-8297-4fdae50eb053.png)

**Comment by bidyut-majumdar** [comment]
@Anupriyabanger please check this issue thoroughly to ensure if this is still happening or not . If still happening then share test case .
