### ISSUE TITLE
Personal video call > Not working

### ISSUE THREAD

**Issue by Anupriyabanger** [Bitovn/Bridge-issues#203]
Upon clicking the video call option in the personal chat, it is showing the result to select meeting ( same as group meeting).
![image](https://user-images.githubusercontent.com/109590553/199457830-b7bd9b9f-2a23-4aa3-ac1f-93683ac311d1.png)

**Comment by bidyut-majumdar** [comment]
Removing as instead of modal personal call to be directly initiated from chat window only
