### ISSUE TITLE
Profile Dropdown > Broken UI

### ISSUE THREAD

**Issue by manojnegi07** [Bitovn/Bridge-issues#205]
![image](https://user-images.githubusercontent.com/92147060/199716505-8b97fcfb-b72f-4e68-b4f0-8f2dd4cbd62e.png)

**Comment by bidyut-majumdar** [comment]
@jagdish-vayuz @Anupriyabanger  Please check this issue on your devices if data not coming or UI is breaking anywhere. Need test case for it as its not appearing for me.

**Comment by Anupriyabanger** [comment]
@bidyut-majumdar it is breaking on a few devices.
