### ISSUE TITLE
New chat is confusing> Bad UX

### ISSUE THREAD

**Issue by technicalbirdVayuz** [Bitovn/Bridge-issues#218]

**Comment by technicalbirdVayuz** [comment]
Also, same layout issues

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/199808312-48074a3c-7ba8-43e9-94bb-2366af0482b2.png)

**Comment by bidyut-majumdar** [comment]
@technicalbirdVayuz Could you please explain the confusion ?

**Comment by bidyut-majumdar** [comment]
@jagdish-vayuz it was done from my side yesterday (as showed), please set condition so that when new chat is opened then the header most search bar gets hidden
