### ISSUE TITLE
Creating a Group > Illustration does not making any sense to me, seems unrelated

### ISSUE THREAD

**Issue by technicalbirdVayuz** [Bitovn/Bridge-issues#219]
![image](https://user-images.githubusercontent.com/18699624/199808470-8ed0cc92-45d8-4d5a-be21-13d41b62ef2b.png)

**Comment by Anupriyabanger** [comment]
@bidyut-majumdar add illustration here
@jagdish-vayuz  Change 2nd line to -"Send your first message to create new group"
