### ISSUE TITLE
Chat > tooltip should be there when hover on icons

### ISSUE THREAD

**Issue by technicalbirdVayuz** [Bitovn/Bridge-issues#232]
![image](https://user-images.githubusercontent.com/18699624/199811615-d2947096-86ff-4e64-bc78-2deb9ba81d93.png)

**Comment by Anupriyabanger** [comment]
Hover is not applied on all icons @bidyut-majumdar 
![image](https://user-images.githubusercontent.com/109590553/201267482-5fae6cae-cdc1-4aa5-aee3-44ce63bd3d5b.png)
