### ISSUE TITLE
Chat> Start New chat illustration poping up again and again

### ISSUE THREAD

**Issue by Anupriyabanger** [Bitovn/Bridge-issues#239]
The illustration appears again and again repeatedly. 
Once it appears, it should stay, as long as the no new message is sent.
![Screenshot (127)](https://user-images.githubusercontent.com/109590553/200765595-342852d7-37c8-4bb8-b27f-9844ab39acd9.png)

**Comment by bidyut-majumdar** [comment]
Tej sir had suggested some other type of animations with different messages, will place these later as not an issue
