### ISSUE TITLE
Chat> User not active status not correct

### ISSUE THREAD

**Issue by Anupriyabanger** [Bitovn/Bridge-issues#258]
![image](https://user-images.githubusercontent.com/109590553/201281538-5bb65881-331b-4e4a-9c22-9907c5e1d0b9.png)

**Comment by bidyut-majumdar** [comment]
@Anupriyabanger  what is not correct here ?

**Comment by Anupriyabanger** [comment]
Active status not correct @jagdish-vayuz 
![image](https://user-images.githubusercontent.com/109590553/205899545-25808b6a-9c52-4f7d-b596-df51bfa756c1.png)
