### ISSUE TITLE
Add group member > Add button should be  always visible

### ISSUE THREAD

**Issue by manojnegi07** [Bitovn/Bridge-issues#282]
![image](https://user-images.githubusercontent.com/92147060/201658051-21d8e6d5-7437-4cb9-8eb5-460fdc1d88a2.png)

![image](https://user-images.githubusercontent.com/92147060/201658163-9cf5a163-1309-4faa-a8c5-4b4ff2dd3b65.png)

**Comment by Anupriyabanger** [comment]
Replace close button with add button.
![image](https://user-images.githubusercontent.com/109590553/202474790-3e19530c-c04b-4cd8-8362-dcc878d052c6.png)
