### ISSUE TITLE
Group > Add member

### ISSUE THREAD

**Issue by manojnegi07** [Bitovn/Bridge-issues#284]
If i am not selecting checks then it is not adding user
![image](https://user-images.githubusercontent.com/92147060/201659794-1d5f098a-c163-401f-8918-98b648a9f671.png)

**Comment by Anupriyabanger** [comment]
If i am not sharing any history, and user is added to group without sharing any history. Pop up is not required.
![image](https://user-images.githubusercontent.com/109590553/202473245-ffb0f132-8770-410f-b7cb-1335b911cd8d.png)
