### ISSUE TITLE
New chat > When searching people it should display the result real-time, without pressing enter etc

### ISSUE THREAD

**Issue by bidyut-majumdar** [Bitovn/Bridge-issues#287]
![2022-11-16_141311](https://user-images.githubusercontent.com/78781245/202131698-ededf66c-7fef-40ca-8c94-192f7e82a21a.png)

@jagdish-vayuz  what we discussed on today's call.

**Comment by Anupriyabanger** [comment]
@jagdish-vayuz Still had to press enter for search result.
