### ISSUE TITLE
Chat> had to scroll up for first message

### ISSUE THREAD

**Issue by Anupriyabanger** [Bitovn/Bridge-issues#295]
![image](https://user-images.githubusercontent.com/109590553/202442065-df9b9226-9642-4f2c-b5aa-0915208b1b45.png)

**Comment by bidyut-majumdar** [comment]
@jagdish-vayuz please check on this, on first message or new message opening its appearing as bit scrolled down .

**Comment by bidyut-majumdar** [comment]
scroll point or something like that needs to be set on this I believe
