### ISSUE TITLE
Chat> Listing> highlight the selected chat

### ISSUE THREAD

**Issue by Anupriyabanger** [Bitovn/Bridge-issues#305]
![image](https://user-images.githubusercontent.com/109590553/202445710-083d60e1-0f6b-4d98-b8d7-51930f36f73c.png)

**Comment by bidyut-majumdar** [comment]
@jagdish-vayuz  this was discussion and share with you with the class "bridge-message-highlight" to be added inside the "chatting" class, adding screenshot:

![msg](https://user-images.githubusercontent.com/78781245/202447091-d9488e54-995b-40f9-b609-4d030145a91c.png)

**Comment by Anupriyabanger** [comment]
@bidyut-majumdar please increase the visibility
