### ISSUE TITLE
chat> Change alert message modal

### ISSUE THREAD

**Issue by Anupriyabanger** [Bitovn/Bridge-issues#309]
![image](https://user-images.githubusercontent.com/109590553/202449243-400c70e6-4da1-4e7a-af1a-7548175e0f19.png)

**Comment by bidyut-majumdar** [comment]
@jagdish-vayuz invalid file alert should come as a toast message since modal acts different way for different purpose .

**Comment by Anupriyabanger** [comment]
Wrong toast msg on Invalid file. @jagdish-vayuz 
![image](https://user-images.githubusercontent.com/109590553/204251186-421b38e4-6ecd-4194-b215-a0103d73a08c.png)
