### ISSUE TITLE
Date appearing multiple times

### ISSUE THREAD

**Issue by technicalbirdVayuz** [Bitovn/Bridge-issues#315]
![image](https://user-images.githubusercontent.com/18699624/202988632-113be556-006f-4454-8bcf-f453f226615b.png)

**Comment by Anupriyabanger** [comment]
@jagdish-vayuz Issue not resolved.
![image](https://user-images.githubusercontent.com/109590553/204243008-b73572cb-270a-43e5-9e33-2acf454b4e32.png)
