### ISSUE TITLE
Make 3 dots horizontal instead of vertical in Reactions

### ISSUE THREAD

**Issue by technicalbirdVayuz** [Bitovn/Bridge-issues#317]

**Comment by bidyut-majumdar** [comment]
@technicalbirdVayuz  its true that horizontal could save space or other, Insight had the same horizontal, but Tej sir had instructed to use vertical (same as social), so its going as similar .

**Comment by technicalbirdVayuz** [comment]
Please increase margin a bit for the 3 dots icons
