### ISSUE TITLE
Chat > message icon should be changed to loader if file is attached

### ISSUE THREAD

**Issue by technicalbirdVayuz** [Bitovn/Bridge-issues#337]

**Comment by Anupriyabanger** [comment]
@jagdish-vayuz Loader is appearing on sending a file, not on attaching the file.  
Also, I was sent an image, and the image was already sent but the loader was revolving.

**Comment by bidyut-majumdar** [comment]
loader attached from my side

**Comment by jagdish-vayuz** [comment]
@bidyut-majumdar please fix loader position on file

**Comment by jagdish-vayuz** [comment]
message icon is changed when the file is being sent
created new issue for loader on file #389
