### ISSUE TITLE
on Refresh, Groups page it should redirect user to the last message

### ISSUE THREAD

**Issue by technicalbirdVayuz** [Bitovn/Bridge-issues#367]

**Comment by Anupriyabanger** [comment]
@jagdish-vayuz Issue not resolved. 
On reloading page it's showing me this screen
![image](https://user-images.githubusercontent.com/109590553/205886001-d14d2666-0071-49a8-b4ae-2dd23108a296.png)

**Comment by jagdish-vayuz** [comment]
@Anupriyabanger loader is not showing like above at my end, Need to see issue in more detail.
And please create new thread for different issue.
