### ISSUE TITLE
 Video call link should be in message box first and the user should be able to send the link to the other members. Right now the link is directly sending on clicking video icon

### ISSUE THREAD

**Issue by jagdish-vayuz** [Bitovn/Bridge-issues#390]

**Comment by Anupriyabanger** [comment]
@jagdish-vayuz issue not resolved.

**Comment by jagdish-vayuz** [comment]
sorry, i have added review required label by mistake

**Comment by Anupriyabanger** [comment]
@jagdish-vayuz no link is updating in my message box.

https://user-images.githubusercontent.com/109590553/207800715-45fe3e0d-79bb-4b2b-8518-f699a6b625a3.mp4
