### ISSUE TITLE
Chat> remove message limit in the chat box 

### ISSUE THREAD

**Issue by Anupriyabanger** [Bitovn/Bridge-issues#408]

**Comment by Anupriyabanger** [comment]
The issue is not resolved, and also now the message I wrote in the chat box got disappears on pressing send button if the length is large.
![image](https://user-images.githubusercontent.com/109590553/209507757-3d2788b2-4b97-43fa-b68f-19d78cb85503.png)

**Comment by jagdish-vayuz** [comment]
character limit set to 5000
