### ISSUE TITLE
Chat> scroll down chat button should be above the Message text box. 

### ISSUE THREAD

**Issue by Anupriyabanger** [Bitovn/Bridge-issues#415]
And the button should appear only on scrolling up.

**Comment by bidyut-majumdar** [comment]
@jagdish-vayuz for the "only on scrolling up" condition your part would be needed.

**Comment by bidyut-majumdar** [comment]
@jagdish-vayuz done the floating part, but seems viewport detection is going wrong,  we need to scroll up bit more than usual to see the  button .
