### ISSUE TITLE
space between two boxes and 3 dots also has lots of gap check screenshot

### ISSUE THREAD

**Issue by Ahlam000** [Bitovn/Bridge-issues#45]
<img width="1406" alt="Screenshot 2022-07-08 at 6 24 09 PM" src="https://user-images.githubusercontent.com/101115620/177996124-bb937f39-9873-47b9-8c6c-8c66fd37cd48.png">

**Comment by technicalbirdVayuz** [comment]
issue is the gap between 3 dots
