### ISSUE TITLE
Video call> settings> selected theme should be highlighted

### ISSUE THREAD

**Issue by Anupriyabanger** [Bitovn/Bridge-issues#462]
No information on if the theme I selected is applied or not. 
Add toast message.
![image](https://user-images.githubusercontent.com/109590553/208880641-e6296b89-9536-48cd-8503-0f636d9ef2dc.png)

**Comment by technicalbirdVayuz** [comment]
For the message, we need to make changes in UI, Added the message but it will be behind the overlay
