### ISSUE TITLE
Email template > OTP not visible on abdul's end

### ISSUE THREAD

**Issue by jagdish-vayuz** [Bitovn/Bridge-issues#469]
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/84120381/209618410-169b9b7c-40e3-408e-9a57-f31cf06777c3.png)

**Comment by bidyut-majumdar** [comment]
@jagdish-vayuz email template has already been shared with you earlier, please check and work on that one for this .

**Comment by technicalbirdVayuz** [comment]
Flow Changed, its removed
