### ISSUE TITLE
check the height when the user turns off the camera 

### ISSUE THREAD

**Issue by Ahlam000** [Bitovn/Bridge-issues#47]
<img width="1440" alt="Screenshot 2022-07-08 at 6 23 35 PM" src="https://user-images.githubusercontent.com/101115620/177998775-c19db658-c5ce-4fde-80d3-35615a250381.png">

**Comment by bidyut-majumdar** [comment]
@jagdish-vayuz  same like #50  , will check and explore before sharing time on video call part , so no timeline for now .

**Comment by Anupriyabanger** [comment]
Issue resolved. 
![image](https://user-images.githubusercontent.com/109590553/212902941-74aa4daf-da58-4cdd-98c6-3865c0749e57.png)
