### ISSUE TITLE
Bridge> OTP modal > Check Description

### ISSUE THREAD

**Issue by naveesha-vayuz** [Bitovn/Bridge-issues#499]
![Screenshot (18)](https://user-images.githubusercontent.com/121479721/212897433-ad6b83eb-726e-4386-8778-4205728e38d2.png)
1) The cursor is blinking on the last input field instead of the first one.

2)  Text Error "A code has been sent to I10142". This should be changed to "A code has been sent to email id".

![Screenshot (19)](https://user-images.githubusercontent.com/121479721/212897532-cc5efacf-f689-4218-bed0-bc89a73d64eb.png)

3) Upon entering the OTP it is not going to next input field.

4) On click of Resend button the OTP input fields should be empty

**Comment by jagdish-vayuz** [comment]
3. you have to press enter then it will move to next field

**Comment by naveesha-vayuz** [comment]
> 3. you have to press enter then it will move to next field

It should automatically go on to next field once the OTP is entered.
