### ISSUE TITLE
Video call > bridge type and host not visible for guest user

### ISSUE THREAD

**Issue by Anupriyabanger** [Bitovn/Bridge-issues#528]
![image](https://user-images.githubusercontent.com/109590553/215444610-632fc5ba-025d-4398-855e-6dfcb3551c9d.png)

**Comment by technicalbirdVayuz** [comment]
This is working already
 
![image](https://github.com/Bitovn/Bridge-issues/assets/18699624/7d7cb0cc-f1e3-428f-bb11-24700428d44b)
