### ISSUE TITLE
Video call> Email should not come from Ankit ID

### ISSUE THREAD

**Issue by Anupriyabanger** [Bitovn/Bridge-issues#532]
Email should come from Bridge.
![image](https://user-images.githubusercontent.com/109590553/215446411-48631ca4-e924-4692-95ca-d97e1b2f37e4.png)

**Comment by technicalbirdVayuz** [comment]
Configured new Email for Sending mails: admin@bridge.vayuz.com

It's done but mails are not getting received on Gmail, Its working fine when sending emails from admin@bridge.vayuz.com to ankit.arora@vayuz.com

**Comment by technicalbirdVayuz** [comment]
Will check this tomorrow, may be initially it require some time for setting up

**Comment by technicalbirdVayuz** [comment]
Fixed
![image](https://github.com/Bitovn/Bridge-issues/assets/18699624/6f9b6a3c-2aaf-40db-9d9b-cc5c0aa4160a)
