### ISSUE TITLE
Video> PIP> labels overlapping

### ISSUE THREAD

**Issue by Anupriyabanger** [Bitovn/Bridge-issues#588]
![image](https://github.com/Bitovn/Bridge-issues/assets/109590553/17235f5b-2d02-4c87-baaf-67964df219c9)

**Comment by technicalbirdVayuz** [comment]
@Anupriyabanger This is a system-generated text which is displayed here & you have used the system's default option for PIP, when we implement this, we need to create our own, thus problem like this would not appear. So technically, it is invalid
