### ISSUE TITLE
Getting "Please rejoin, Error Type: Media." while joining, I have already left the call, but I am still being counted to be on the call, so unable to join again.

### ISSUE THREAD

**Issue by VayuzBidyut** [Bitovn/Bridge-issues#664]
![Screenshot 2023-10-26 181107](https://github.com/Bitovn/Bridge-issues/assets/78781245/593673b4-a5ad-4bbd-a13a-cd8af8f29dfb)

**Comment by technicalbirdVayuz** [comment]
#665

**Comment by technicalbirdVayuz** [comment]
https://github.com/Bitovn/Bridge-issues/issues/665#issuecomment-1788522773
