### ISSUE TITLE
Stuck on this screen. Not able to join call. 

### ISSUE THREAD

**Issue by vayuzpriya** [Bitovn/Bridge-issues#665]
![image](https://github.com/Bitovn/Bridge-issues/assets/81085431/d505c06d-97ad-4c55-a858-a0d5b0e76f8f)

**Comment by technicalbirdVayuz** [comment]
Configured already in meeting for this

Use case: when you leave, then its not always updated that you left. You need to enter using already in meeting link
![unnamed](https://github.com/Bitovn/Bridge-issues/assets/18699624/fdd88464-4998-439a-aad2-46fee5ac7db5)
