### ISSUE TITLE
On Pin User UI breaks

### ISSUE THREAD

**Issue by Ahlam000** [Bitovn/Bridge-issues#667]
<img width="1440" alt="Screenshot 2023-10-30 at 6 56 28 PM" src="https://github.com/Bitovn/Bridge-issues/assets/101115620/4b1f4787-1bb5-4a0a-9132-5e953303fdaa">

**Comment by technicalbirdVayuz** [comment]
This will be removed, its not completely developed

**Comment by technicalbirdVayuz** [comment]
Removed
