### ISSUE TITLE
502 badgateway after 15 min in a meet

### ISSUE THREAD

**Issue by Ahlam000** [Bitovn/Bridge-issues#668]
<img width="1425" alt="Screenshot 2023-10-30 at 7 02 38 PM" src="https://github.com/Bitovn/Bridge-issues/assets/101115620/bf57f7ff-d570-4bbf-8ddf-40cc63ef6b8c">

**Comment by technicalbirdVayuz** [comment]
New build was being uploaded at that time, mentioned in groups also
