### ISSUE TITLE
Getting the shared screen in Scrollable form 

### ISSUE THREAD

**Issue by PrakVayuz** [Bitovn/Bridge-issues#728]
![image](https://github.com/Bitovn/Bridge-issues/assets/158542726/9ee013aa-3eb1-4942-b74e-b2182b961424)
![image](https://github.com/Bitovn/Bridge-issues/assets/158542726/7f340dc4-52eb-4a1a-a3fe-3be7dcedd193)

**Comment by bidyut-majumdar** [comment]
Not able to replicate the issue. Neither happened from my end, nor from @PrakVayuz 's end too.

**Comment by technicalbirdVayuz** [comment]
Lets close this if not replicated in this week

**Comment by VayuzBidyut** [comment]
@technicalbirdVayuz  as discussed, we need to create layout for multiple screen-sharing. Move it to upcoming child sprint.

**Comment by technicalbirdVayuz** [comment]
Duplicate #795

**Comment by technicalbirdVayuz** [comment]
Duplicate
