### ISSUE TITLE
please change the text "Danger" to "Alert"

### ISSUE THREAD

**Issue by VayuzBidyut** [Bitovn/Bridge-issues#729]
Link ex: https://bridge-beta.vayuz.com/room?roomId=abcdabcd

![2024-04-29_121642](https://github.com/Bitovn/Bridge-issues/assets/78781245/73858e27-c8b7-4ad2-80a6-2fec8430b2c1)

**Comment by technicalbirdVayuz** [comment]
The toast is appearing twice, also
