### ISSUE TITLE
Please keep the speaking icon inside a div so it can be separated

### ISSUE THREAD

**Issue by VayuzBidyut** [Bitovn/Bridge-issues#747]
![2024-05-03_095234](https://github.com/Bitovn/Bridge-issues/assets/78781245/863ef09b-e7f5-492c-bbf4-e99dc7ee0ee1)

**Comment by technicalbirdVayuz** [comment]
<h4>{name}</h4>
      <div>
      {#if speaking}
        ~ 🗣️
      {/if}
    </div>
    
is it fine?
