### ISSUE TITLE
Layout gets break when user is not logged in and tries to join the meeting

### ISSUE THREAD

**Issue by technicalbirdVayuz** [Bitovn/Bridge-issues#766]
<img width="863" alt="Screenshot 2024-05-08 at 9 36 57 AM" src="https://github.com/Bitovn/Bridge-issues/assets/18699624/e2231425-2a91-405f-9a25-7ee57f80f047">

**Comment by VayuzBidyut** [comment]
@technicalbirdVayuz  this is old issue
