### ISSUE TITLE
meeting room> screen size for single user can be increased

### ISSUE THREAD

**Issue by Anupriyabanger** [Bitovn/Bridge-issues#767]
Bridge:
![image](https://github.com/Bitovn/Bridge-issues/assets/109590553/a04b17ee-a486-4149-babd-bfdf64704bf8)
Meet:
![image](https://github.com/Bitovn/Bridge-issues/assets/109590553/a76fd9ac-31a5-493c-8266-6f2036392181)

**Comment by VayuzBidyut** [comment]
Increased width from 49% to 60% for desktop .
