### ISSUE TITLE
Meeting room> Participant list showing incorrect details

### ISSUE THREAD

**Issue by Anupriyabanger** [Bitovn/Bridge-issues#775]
![image](https://github.com/Bitovn/Bridge-issues/assets/109590553/72fe7662-777c-404e-b184-f599a51e207a)

**Comment by technicalbirdVayuz** [comment]
Please share the use case if you can replicate

**Comment by technicalbirdVayuz** [comment]
Use case, is when you were with Guest user in meeting!
