### ISSUE TITLE
Attendance room> Add option to rejoin meeting if the other participants are still there on the call

### ISSUE THREAD

**Issue by Anupriyabanger** [Bitovn/Bridge-issues#776]
![image](https://github.com/Bitovn/Bridge-issues/assets/109590553/2661d816-3359-427e-87bf-a3c5ed5c1e8a)

**Comment by technicalbirdVayuz** [comment]
As a user, you are on that page because you are done with the meeting, its not something that you clicked accidentally, will discuss this

**Comment by technicalbirdVayuz** [comment]
Meeting Rejoin option needs to be given

**Comment by soumyadashvayuz** [comment]
Done.
