### ISSUE TITLE
Homepage> Calendar> No need to show meeting link twice 

### ISSUE THREAD

**Issue by Anupriyabanger** [Bitovn/Bridge-issues#778]
User can see the details in the call logs
![image](https://github.com/Bitovn/Bridge-issues/assets/109590553/7b25bef4-3cd9-43eb-ac0c-1bba7a4c2cf2)

**Comment by technicalbirdVayuz** [comment]
Its there because you have joined the same meeting twice, every meeting entrance + exit has to be captured

**Comment by technicalbirdVayuz** [comment]
Group By meeting Id

**Comment by technicalbirdVayuz** [comment]
![Image](https://github.com/Bitovn/Bridge-issues/assets/18699624/8746e9e8-b091-4e5a-b8b3-ae6b28577ff0)

Meeting count added here, last meeting will be showcased on the top (based on filter, recently created)

**Comment by soumyadashvayuz** [comment]
Good to go
