### ISSUE TITLE
Create Room > Create bridge button should be active only when the details are filled by the user otherwise instant meeting button should be active

### ISSUE THREAD

**Issue by Anupriyabanger** [Bitovn/Bridge-issues#781]
it looks like the instant button is not clickable
![image](https://github.com/Bitovn/Bridge-issues/assets/109590553/a0980f03-8b06-41df-878c-1605b7198576)

**Comment by technicalbirdVayuz** [comment]
@VayuzBidyut functionality added, please improve the UX for Create insight meeting button
