### ISSUE TITLE
Add tag of Host for the call host on the participant list

### ISSUE THREAD

**Issue by Anupriyabanger** [Bitovn/Bridge-issues#787]
![image](https://github.com/Bitovn/Bridge-issues/assets/109590553/2a43abe8-3659-4b38-8f31-07b595cfbaaf)

**Comment by technicalbirdVayuz** [comment]
<img width="310" alt="Screenshot 2024-05-23 at 1 15 15 PM" src="https://github.com/Bitovn/Bridge-issues/assets/18699624/5dfdf0f5-11a7-4ca9-a0cf-d2b37269ced7">

**Comment by milivayuz** [comment]
![Uploading image.png…]()

Still not showing
