### ISSUE TITLE
Accept the guest pop up is not showing up anywhere

### ISSUE THREAD

**Issue by milivayuz** [Bitovn/Bridge-issues#789]
<img width="959" alt="image" src="https://github.com/Bitovn/Bridge-issues/assets/156641922/964850f4-ccb0-4dd7-93de-d2593b6966fa">
<img width="959" alt="image" src="https://github.com/Bitovn/Bridge-issues/assets/156641922/711c7e0a-d5b2-4cf1-84d2-f49b2652b084">

Accept the guest pop-up is not showing up anywhere

**Comment by technicalbirdVayuz** [comment]
Please re-check

**Comment by technicalbirdVayuz** [comment]
& share the use case if possible
