### ISSUE TITLE
Unable to Create Meeting 

### ISSUE THREAD

**Issue by milivayuz** [Bitovn/Bridge-issues#790]
https://github.com/Bitovn/Bridge-issues/assets/156641922/1f85b039-9ea8-45df-bfc7-9fd6e4df5e30

In case I have to sign in to create a meeting then show me a pop up to sign in

**Comment by technicalbirdVayuz** [comment]
Its added already, can you check this again or share the use case 

https://github.com/Bitovn/Bridge-issues/assets/18699624/ecf0b27a-0f8d-4234-b151-60a5dcdff12a

**Comment by technicalbirdVayuz** [comment]
Working now
