### ISSUE TITLE
On Scroll im able to see the presentation

### ISSUE THREAD

**Issue by naveesha-vayuz** [Bitovn/Bridge-issues#795]
![image](https://github.com/Bitovn/Bridge-issues/assets/121479721/b816c0f6-ddc7-497e-9d9c-9ba9e3efba3c)
This is on scroll

![image](https://github.com/Bitovn/Bridge-issues/assets/121479721/8c9d31dc-755d-4b3c-9ec9-650914c939ab)
First screen

Connect with me in case you are not able to understand

**Comment by soumyadashvayuz** [comment]
Working fine now.
