### ISSUE TITLE
Use case: in case the host enters the meet after guest. The guest's request to enter in the meet is not shown

### ISSUE THREAD

**Issue by milivayuz** [Bitovn/Bridge-issues#796]
<img width="959" alt="image" src="https://github.com/Bitovn/Bridge-issues/assets/156641922/fa05f493-ecb0-4218-9845-118560cc0fb2">
<img width="959" alt="image" src="https://github.com/Bitovn/Bridge-issues/assets/156641922/b509c4f4-5c21-4fa6-8732-2aa773c4e341">

**Comment by soumyadashvayuz** [comment]
Working now
