### ISSUE TITLE
On the same meeting still not visible to each other

### ISSUE THREAD

**Issue by milivayuz** [Bitovn/Bridge-issues#799]
<img width="959" alt="image" src="https://github.com/Bitovn/Bridge-issues/assets/156641922/c6e46505-d8e2-4c0a-8be3-a16067a1b521">
<img width="594" alt="image" src="https://github.com/Bitovn/Bridge-issues/assets/156641922/9d960cd5-84e1-44e5-bd8d-f8cf0eb17c71">

**Comment by technicalbirdVayuz** [comment]
Currently, this is because of Brave Browser, checked in Mac using Brave working  fine

**Comment by technicalbirdVayuz** [comment]
Working in Chrome

**Comment by soumyadashvayuz** [comment]
Working now
