### ISSUE TITLE
Share analytics of this bridge code: 

### ISSUE THREAD

**Issue by milivayuz** [Bitovn/Bridge-issues#890]
https://bridge-beta.vayuz.com/join-meeting?roomId=m3idh7u5

**Comment by technicalbirdVayuz** [comment]
![screencapture-bridge-beta-vayuz-bridge-analysis-m3idh7u5-2024-12-02-09_59_29-compressed](https://github.com/user-attachments/assets/d37d9990-48e9-4272-9402-3f13a0fc109a)
